# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cogni-candidate-a

resources:
  - ../../../base/poly-test-worker

# Image digest — overwritten by promote-k8s-image.sh on first promote.
images:
  - name: ghcr.io/cogni-dao/poly-test-worker
    newName: ghcr.io/cogni-dao/poly-test-worker
    digest: "sha256:e0efd2d35cf03d13f22eb43afc3527b6108991341f62c789ba1122c530a79c27"
