# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cogni-candidate-a

resources:
  - ../../../base/poly-test-worker

# Image digest — overwritten by promote-k8s-image.sh on first promote.
images:
  - name: ghcr.io/cogni-dao/poly-test-worker
    newName: ghcr.io/cogni-dao/poly-test-worker
    digest: "sha256:8ba06f05a7eb5819e8b433775e8c5c33bd7167e4a8883a12ec1fe991b4fc8db6"
