# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cogni-preview

resources:
  - ../../../base/poly-test-worker

# Image digest — overwritten by promote-k8s-image.sh on first promote.
images:
  - name: ghcr.io/cogni-dao/poly-test-worker
    newName: ghcr.io/cogni-dao/poly-test-worker
    digest: "sha256:d08f363076fde238ec1c0f016da9d76a8e7b56961b74aa0152fb2f36e8cbd408"
